services:
  - type: web
    name: django-be
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: >
      python manage.py migrate --noinput &&
      gunicorn backend.wsgi:application
    healthCheckPath: /api/form/
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: be-postgres
          property: externalConnectionString

databases:
  - name: be-postgres
    plan: free
